### PR TITLE
Fix jumping bug

### PR DESCRIPTION
**Pull request by APeng215**
## What is the request for?

This pull request is aimed at fixing #2 

## How does the request do?
I just set a field `jumpingCount` for `Player` class and resets the `jumpingCount` according to `Player#checkForVerticalCollisions` if you are on the ground.

### CODE REVIEW

**Comment by MarkfuGod** [comment]
*Thanks for ur help!*
However, the newly adjusted code reveals a bug that when 'w' is pressed down, the character will jump constantly.

**Comment by MarkfuGod** [comment]
You could modify the keyboard event listener and add a judge function to detect whether the 'w' key is pressed down by the player continuously.

**Comment by APeng215** [comment]
Could you ***reopen*** this PR? So that I can still add more commits to this PR to fix the revealed bug.

**Comment by MarkfuGod** [comment]
sorry pal, forgot to reopen it

**Comment by APeng215** [comment]
It's ok. I have added a new commit https://github.com/MarkfuGod/Commissaire/pull/3/commits/797464b16b8d9c38e637e28121686948ea4a5e03 to fix the bug you revealed. You can check it now.

**Pull request merged**
